# -*- coding: utf-8 -*-
"""Calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KcOyn6GtnEK807cXTPO-MM5-_mAMDM0L
"""

import sqlite3

def create_database():
    #Create a SQLite database to store calculation history.
    conn = sqlite3.connect("calculator_history_console.db")
    cursor = conn.cursor()
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS history (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            operation TEXT,
            result REAL
        )
    """)
    conn.commit()
    conn.close()

def save_to_history(operation, result):
    #Save the calculation history in SQLite database.
    conn = sqlite3.connect("calculator_history.db")
    cursor = conn.cursor()
    cursor.execute("INSERT INTO history (operation, result) VALUES (?, ?)", (operation, result))
    conn.commit()
    conn.close()

def calculator():
    #Console-based calculator that performs basic arithmetic operations.
    while True:
        print("\nSimple Calculator")
        print("1. Addition (+)")
        print("2. Subtraction (-)")
        print("3. Multiplication (*)")
        print("4. Division (/)")
        print("5. View History")
        print("6. Exit")

        choice = input("Choose an operation: ")

        if choice == "6":
            print("Exiting the calculator.")
            break
        elif choice == "5":
            view_history()
            continue

        try:
            num1 = float(input("Enter first number: "))
            num2 = float(input("Enter second number: "))

            if choice == "1":
                result = num1 + num2
                operation = f"{num1} + {num2} = {result}"
            elif choice == "2":
                result = num1 - num2
                operation = f"{num1} - {num2} = {result}"
            elif choice == "3":
                result = num1 * num2
                operation = f"{num1} * {num2} = {result}"
            elif choice == "4":
                if num2 == 0:
                    print("Error: Division by zero is not allowed.")
                    continue
                result = num1 / num2
                operation = f"{num1} / {num2} = {result}"
            else:
                print("Invalid choice. Please try again.")
                continue

            print(f"Result: {result}")
            save_to_history(operation, result)

        except ValueError:
            print("Invalid input. Please enter numbers only.")

def view_history():
    #Retrieve and display calculation history from SQLite database.
    conn = sqlite3.connect("calculator_history.db")
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM history")
    rows = cursor.fetchall()

    if rows:
        print("\nCalculation History:")
        for row in rows:
            print(f"{row[1]}")
    else:
        print("No history available.")

    conn.close()

if __name__ == "__main__":
    create_database()
    calculator()

